version: '2'

services:
  postgres:
    image: postgres
    container_name: postgresql-container
    ports:
      - "5432:5432"
    volumes: 
      - ./:/assignment
    environment: 
      - POSTGRES_PASSWORD=somePassword
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    ports:
      - "5050:80"
    environment: 
      - PGADMIN_DEFAULT_EMAIL=mirmahathir1@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=somePassword
